// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALJ6XoxvE1tvQ9YCJtoI_ETQzRmXBd3b0',
    appId: '1:155988113639:android:7f9726e67b1c57c7688a42',
    messagingSenderId: '155988113639',
    projectId: 'pengingat-pr',
    storageBucket: 'pengingat-pr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAolBYhEGXadoxFa7KoLphWnBuUflOxAHk',
    appId: '1:155988113639:ios:1e7a52b00f99db49688a42',
    messagingSenderId: '155988113639',
    projectId: 'pengingat-pr',
    storageBucket: 'pengingat-pr.firebasestorage.app',
    androidClientId: '155988113639-hdshp24ibnmo9t3tbv7q1qrcte4s2si9.apps.googleusercontent.com',
    iosClientId: '155988113639-tcfj82olnstbfdsrops54mir3f587f0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.pengingatPr',
  );

}